In [2]:
with open('spam.csv','r') as f1:
   print(f1,type(f1))

<_io.TextIOWrapper name='spam.csv' mode='r' encoding='cp1252'> <class '_io.TextIOWrapper'>


In [3]:
import pandas as pd 
df= pd.read_csv('spam.csv',encoding='cp1252')

In [4]:
df

v1                                                 v2 Unnamed: 2  \
0      ham  Go until jurong point, crazy.. Available only ...        NaN   
1      ham                      Ok lar... Joking wif u oni...        NaN   
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3      ham  U dun say so early hor... U c already then say...        NaN   
4      ham  Nah I don't think he goes to usf, he lives aro...        NaN   
...    ...                                                ...        ...   
5567  spam  This is the 2nd time we have tried 2 contact u...        NaN   
5568   ham              Will Ì_ b going to esplanade fr home?        NaN   
5569   ham  Pity, * was in mood for that. So...any other s...        NaN   
5570   ham  The guy did some bitching but I acted like i'd...        NaN   
5571   ham                         Rofl. Its true to its name        NaN   

     Unnamed: 3 Unnamed: 4  
0           NaN        NaN  
1           NaN        NaN  
2           NaN        NaN  
3           NaN        NaN  
4           NaN        NaN  
...         ...        ...  
5567        NaN        NaN  
5568        NaN        NaN  
5569        NaN        NaN  
5570        NaN        NaN  
5571        NaN        NaN  

[5572 rows x 5 columns]

In [5]:
df.rename(columns={'v1':'class_labels','v2':'messages'}, inplace=True)

In [6]:
df.drop(['Unnamed: 2','Unnamed: 3','Unnamed: 4'],axis=1,inplace=True)


In [7]:
df

class_labels                                           messages
0             ham  Go until jurong point, crazy.. Available only ...
1             ham                      Ok lar... Joking wif u oni...
2            spam  Free entry in 2 a wkly comp to win FA Cup fina...
3             ham  U dun say so early hor... U c already then say...
4             ham  Nah I don't think he goes to usf, he lives aro...
...           ...                                                ...
5567         spam  This is the 2nd time we have tried 2 contact u...
5568          ham              Will Ì_ b going to esplanade fr home?
5569          ham  Pity, * was in mood for that. So...any other s...
5570          ham  The guy did some bitching but I acted like i'd...
5571          ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [8]:
class_labels_values = {
    'ham': 0,
    'spam': 1
}
df['class_labels'] = df['class_labels'].map(class_labels_values)

In [9]:
df

class_labels                                           messages
0                0  Go until jurong point, crazy.. Available only ...
1                0                      Ok lar... Joking wif u oni...
2                1  Free entry in 2 a wkly comp to win FA Cup fina...
3                0  U dun say so early hor... U c already then say...
4                0  Nah I don't think he goes to usf, he lives aro...
...            ...                                                ...
5567             1  This is the 2nd time we have tried 2 contact u...
5568             0              Will Ì_ b going to esplanade fr home?
5569             0  Pity, * was in mood for that. So...any other s...
5570             0  The guy did some bitching but I acted like i'd...
5571             0                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [10]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(df['messages'],df['class_labels'],test_size=0.3,random_state=42)


In [11]:
y_train.value_counts()

class_labels
0    3372
1     528
Name: count, dtype: int64

In [12]:
y_test.value_counts()

class_labels
0    1453
1     219
Name: count, dtype: int64

In [13]:
#convertion into string to numeric  using countvectorizer 
# mean string into vector [0,0,0,0,1,0,7,0,6] 
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer(lowercase= True, stop_words='english')


In [20]:
x_train_transformed = vectorizer.fit_transform(x_train)
x_test_transformed = vectorizer.transform(x_test)


In [21]:
x_train_transformed

<3900x6946 sparse matrix of type '<class 'numpy.int64'>'
	with 30413 stored elements in Compressed Sparse Row format>

In [22]:
x_train_transformed.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [23]:
from sklearn.naive_bayes import MultinomialNB
classifier = MultinomialNB()


In [24]:
classifier.fit(x_train_transformed, y_train)
ytest_predicted_labels = classifier.predict(x_test_transformed)

In [25]:
ytest_predicted_labels

array([0, 0, 1, ..., 0, 0, 0], dtype=int64)

In [26]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

print("accuray score:",accuracy_score(y_test,ytest_predicted_labels ))
print("confusion matrix:",confusion_matrix(y_test,ytest_predicted_labels ))
print("classification report:",classification_report(y_test,ytest_predicted_labels ))


accuray score: 0.9832535885167464
confusion matrix: [[1442   11]
 [  17  202]]
classification report:               precision    recall  f1-score   support

           0       0.99      0.99      0.99      1453
           1       0.95      0.92      0.94       219

    accuracy                           0.98      1672
   macro avg       0.97      0.96      0.96      1672
weighted avg       0.98      0.98      0.98      1672



In [27]:
new_email="please call and collect the prize"

In [28]:
new_email_transformed=vectorizer.transform([new_email])
new_email_transformed

<1x6946 sparse matrix of type '<class 'numpy.int64'>'
	with 2 stored elements in Compressed Sparse Row format>

In [29]:
new_email_transformed.toarray()

array([[0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [30]:
classifier.predict(new_email_transformed)

array([1], dtype=int64)